**Pontia Tech - Master Data Analytics - Visualización de Datos con Python**

***
Datos del alumno (Nombre y Apellidos): Vicente Alba Martínez

Fecha: 12/07/2026
***

<span style="font-size: 30pt; font-weight: bold; color: #0098cd;">Estudio Politica Descuentos Pontia SuperStore</span>

<span style="font-size: 15pt; font-weight: bold; color: #0098cd;">Sesión Live Práctica</span>

Entregable Visualización Python

**Objetivos**

El objetivo de este caso práctico es realizar un estudio de como ha impactado la politica de descuentos a la rentabilidad de la empresa Pontia SuperStore. Para ello usaremos la librería Plotly para la elaboración de gráficos Interactivos.

**Enunciado**

Somos parte del equipo de datos de la empresa PontiaSuperStore han encargado hacer un estudio de cómo ha impactado la politica de descuentos en la rentabilidad de la empresa.

Para ello contamos con un dataset con los pedidos efectuados a la empresa. En cada pedido hay una columna que nos informa del % de descuento que lleva esa venta asociada. ¿Esta afectando a la rentabilidad de la empresa? ¿Es igual para todos los productos?

Elabora un reporte usando python que contenga diferentes visualizaciones ilustrando el problema.

Trata de no pensar directamente en la solución y construye una historia a traves de los datos.

**Requisitos de la actividad:**

1º El reporte debe contener mínimo tres visualizaciones. Recomendación: Es interesante pensar en una estructura introducción - nudo - desenlace. En la que se presenta el problema primero, se aportan diferentes puntos de vista y se da una solución.

2º Utilización de Plotly para resolver el ejercicio.

3º Entregar el Notebook con las respuestas argumentadas, no solo el gráfico.

<span style="font-size: 20pt; font-weight: bold; color: #0098cd;">1. Importación Librerías y Carga Datos</span>

<span style="font-size: 15pt; font-weight: bold; color: #0098cd;">1.1. Importación Librerías</span>

In [28]:
# Librerías Procesamiento de Datos.
import pandas as pd
import numpy as np

# Librería de Visualización
import plotly.express as px

# Avoid Warnings
import warnings
warnings.filterwarnings('ignore')

In [29]:
%matplotlib inline

<span style="font-size: 15pt; font-weight: bold; color: #0098cd;">1.2. Carga de Datos</span>

La carga de los datos la podemos hacer en Colab usando la librería "io" o en local.

Google Colab

In [30]:
## En Google Colab
from google.colab import files
uploaded = files.upload()

Saving PontiaSuperStore.xls to PontiaSuperStore (2).xls

In [34]:
import io
df = pd.read_excel(io.BytesIO(uploaded["PontiaSuperStore (2).xls"]))
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714

En local

In [ ]:
# Solamente en caso de no usar Google Colab.
# df = pd.read_excel("PontiaSuperStore.xls", sheet_name="Orders")

<span style="font-size: 15pt; font-weight: bold; color: #0098cd;">1.3. Generación de variables calculadas.</span>

Genere a partir del dataframe cargado las siguientes variables calculadas.

- Sales/Quantity: Precio de Venta por unidad de producto en cada operación de venta
- Profit/Quantity: Beneficio por unidad de producto en cada operación de venta
- flag_descuento: Marca con "Con Descuento" si esa operacion de venta ha tenido descuento (esto es descuento>0), "Sin Descuento" si no.
- Year: Variable con el año de la fecha de la operación de venta.

Respuesta:

Generamos las variables calculadas que nos pide el ejercicio:

In [35]:
df["Sales/Quantity"] = (df.Sales)/(df.Quantity)
df["Profit/Quantity"] = (df.Profit)/(df.Quantity)
df["Flag_descuento"] = np.where(df["Discount"] > 0, "Con descuento", "Sin descuento")
df["Year"] = df["Order Date"].dt.year.astype(str)

df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Sales/Quantity,Profit/Quantity,Flag_descuento,Year
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136,130.98,20.9568,Sin descuento,2016
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820,243.98,73.1940,Sin descuento,2016
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714,7.31,3.4357,Sin descuento,2016

<span style="font-size: 20pt; font-weight: bold; color: #0098cd;">2. Estudio Descuentos PontiaSuperStore</span>

Elaboración del reporte.

Argumenta y explica la motivación del gráfico así como sus enunciados.

<span style="font-size: 15pt; font-weight: bold; color: #0098cd;">2.1. Gráfico 1.</span>

Respuesta: Vamos a analizar primero si hay relación entre el Precio de Venta por unidad de producto en cada operación de venta medido por la nueva variable que hemos creado llamada Sales/Quantity con la aplicación de descuento en el caso de que así sea.

In [36]:
fig_discount = px.pie(df, names= "Flag_descuento", title = "Ventas con y sin descuento")
fig_discount.show()

Conclusiones:

Como podemos ver en el gráfico anterior, la mayoría de las ventas son con descuento (52%). Ello nos indica que dentro de la actividad de ventas de la empresa, las ventas con descuento son muy importantes dentro del volumen total de ventas.

<span style="font-size: 15pt; font-weight: bold; color: #0098cd;">2.2. Gráfico 2.</span>

Respuesta: Vamos a analizar el impacto en el beneficio de la empresa según el tipo de descuento aplicado.

In [37]:
fig_discount_regresion = px.scatter(df, x="Discount", y="Profit", color="Flag_descuento")
fig_discount_regresion.show()

Como podemos ver en el gráfico, cuando la empresa no aplica descuentos (descuento = 0), todas las ventas tienen beneficios. Cuando en cambio si se aplican descuentos, vemos que hasta 30% de descuento aproximadamente, la empresa sigue teniendo mayoritariamente beneficios, pero a partir del 40% de descuento, ya registra pérdidas en la mayoría de las ventas. Por lo tanto, podemos concluir que o la empresa no está teniendo en cuenta el margen que tiene realmente al aplicar descuentos grandes o bien, le compensa de forma indirecta por otros medios.

Vamos a ver ahora el beneficio anual en ventas con y sin descuento

In [38]:
df_agrupado = df.groupby(["Year", "Flag_descuento"])["Profit"].mean().reset_index()
df_agrupado.head(10)

df_agrupado = px.bar(
    df_agrupado,
    x="Year",
    y="Profit",
    color="Flag_descuento",
    barmode="group",
    title="Beneficio Promedio por año (Con/Sin descuento)",
    labels ={"Profit": "Beneficio Promedio", "Year": "Año"}
)
df_agrupado.show()

Conclusiones:

Como podemos ver, el beneficio medio de las ventas sin descuento es positivo mientras que las ventas con descuento registran márgenes medios negativos. Si bien entre 2014 y 2016 se reducen las pérdidas medias en las ventas con descuento, en 2017 vuelven a repuntar ligeramente. Las ventas sin descuento también mejoran su margen medio entre 2014 y 2016 pero en 2017 bajan un poco.

<span style="font-size: 15pt; font-weight: bold; color: #0098cd;">2.3. Gráfico 3.</span>

Respuesta: Vamos a analizar la correlación entre ventas y beneficio por categorias con y sin descuento

In [39]:
correlacion = df["Sales/Quantity"].corr(df["Profit/Quantity"])
print(f"El coeficiente de correlación es: {correlacion}")

fig =px.scatter (df,
                x="Sales/Quantity",
                y="Profit/Quantity",
                color="Flag_descuento",
                symbol="Category",
                trendline="ols",
                title="Relación entre Descuento y Beneficio")
fig.update_layout(width=900, height=500)
fig.show()

El coeficiente de correlación es: 0.5382151710074112

Viendo la correlación por categorías entre beneficio y ventas, con y sin descuento aplicado, podemos observar que en general, las categorías sin descuento tienen una correlación positiva, con lo que interesa seguir sin aplicar descuentos, ya que la tendencia es claramente al alza. En cuanto a la correlación en las categorías con descuento, vemos claramente una tendencia cercana a 0, por lo que no podríamos asegurar que a mayor descuento, mayores ventas.

Conclusiones:

Viendo toda la información que nos detallan los gráficos anteriores, podemos concluir que:

- La empresa tiene un mayor volumen de ventas en artículos con descuento (52%)
- A partir del 30% de descuento, las ventas en las que se aplique registran mayoritariamente pérdidas.
- Analizando el beneficio promedio anual, vemos que entre 2014 y 2016 se redujeron las pérdidas medias en las ventas con descuento y se mejoró el beneficio medio de las ventas sin descuento, aunque en 2017 hubo una ligera reducción de márgenes en ambos.
- Podemos concluir que no hay una correlación positiva entre descuento y beneficios, por lo que a mayores descuentos no conseguiremos mejores resultados.